// leave off @2x/@3x
const images = {
  logo: require('../Images/logo.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-logo.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  signupButton: require('../Images/signup-btn.png'),
  loginButton: require('../Images/login-btn.png'),
  backButton: require('../Images/arrow-back.png'),
  forwardButton: require('../Images/arrow-forward.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  productIcon: require('../Images/product-icon.png'),
  productPlaceholder: require('../Images/product-placeholder.png'),
  cartIcon: require('../Images/cart-icon.png'),
  historyIcon: require('../Images/history-icon.png'),
  itemIcon: require('../Images/item-icon.png'),
  itemPlaceholder: require('../Images/item-placeholder.png'),
  largePlus: require('../Images/LargePlus.png'),
  headerLogo: require('../Images/header-logo.png'),
  profilePlaceholder: require('../Images/profile-placeholder.png'),
  dropdownCancel: require('../Images/Dropdown/cancel.png'),
  dropdownInfo: require('../Images/Dropdown/info.png'),
  dropdownWarn: require('../Images/Dropdown/warn.png'),
  dropdownError: require('../Images/Dropdown/error.png'),
  dropdownNotification: require('../Images/cloud-56x56.png'),
}

export default images
